theme: jekyll-theme-minimal
title: "Extinction Rebellion South East Queensland Community Page"
url: "https://zebrax0r.github.io/xrseq"
logo: "images/xrlogo.png"
# show_downloads: "true"
# description: "This site has been built to provide an information repository, blog and communications mechanism for the SEQ XR movement."
